                                   REVENUE ANALYSIS BY PRODUCT CATEGORY

                       QUESTION:
   Finance wants to know the total revenue generated by each product category to inform inventory and marketing investment decisions. Show me product categories sorted by revenue from highest to lowest.

           QUERY
   SELECT 
    Product_Category,
    SUM(Total_Purchase_Amount) AS total_revenue
FROM transactions
GROUP BY Product_Category
ORDER BY total_revenue DESC;

                KEY FINDINGS:
 Books generated the highest revenue at $204.9M (30.1%), followed by Clothing at $204.5M (30.0%). Electronics and Home categories each contributed approximately $136M (20%). 
This balanced product mix indicates no over-reliance on a single category. 

                  RECOMMENDATION: 
Ensure enough stock of Books and Clothing while exploring growth opportunities in Electronics and Home categories through targeted promotions.
